---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- nonResourceURLs:
  - /.well-known/openid-configuration
  - /openid/v1/jwks
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alialjaffer.ziti
  resources:
  - zitiaccesspolicies
  - zitiapps
  - ziticas
  - ziticonnections
  - zitiidentities
  - zitijwtsigners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alialjaffer.ziti
  resources:
  - zitiaccesspolicies/finalizers
  - zitiapps/finalizers
  - ziticas/finalizers
  - ziticonnections/finalizers
  - zitiidentities/finalizers
  - zitijwtsigners/finalizers
  verbs:
  - update
- apiGroups:
  - alialjaffer.ziti
  resources:
  - zitiaccesspolicies/status
  - zitiapps/status
  - ziticas/status
  - ziticonnections/status
  - zitiidentities/status
  - zitijwtsigners/status
  verbs:
  - get
  - patch
  - update
