---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ziti.k8s.openziti.io
  resources:
  - ziticonnections
  - zitiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ziti.k8s.openziti.io
  resources:
  - ziticonnections/finalizers
  - zitiservices/finalizers
  verbs:
  - update
- apiGroups:
  - ziti.k8s.openziti.io
  resources:
  - ziticonnections/status
  - zitiservices/status
  verbs:
  - get
  - patch
  - update
