---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- nonResourceURLs:
  - /.well-known/openid-configuration
  - /openid/v1/jwks
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ziti.alialjaffer.com
  resources:
  - zitiaccesspolicies
  - zitiapps
  - ziticas
  - ziticonfigs
  - ziticonnections
  - zitiedgerouterpolicies
  - zitiidentities
  - zitijwtsigners
  - zitirouters
  - zitiserviceedgerouterpolicies
  - zitiservicepolicies
  - zitiservices
  - zitisidecars
  - zititerminators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ziti.alialjaffer.com
  resources:
  - zitiaccesspolicies/finalizers
  - zitiapps/finalizers
  - ziticas/finalizers
  - ziticonfigs/finalizers
  - ziticonnections/finalizers
  - zitiedgerouterpolicies/finalizers
  - zitiidentities/finalizers
  - zitijwtsigners/finalizers
  - zitirouters/finalizers
  - zitiserviceedgerouterpolicies/finalizers
  - zitiservicepolicies/finalizers
  - zitiservices/finalizers
  - zitisidecars/finalizers
  - zititerminators/finalizers
  verbs:
  - update
- apiGroups:
  - ziti.alialjaffer.com
  resources:
  - zitiaccesspolicies/status
  - zitiapps/status
  - ziticas/status
  - ziticonfigs/status
  - ziticonnections/status
  - zitiedgerouterpolicies/status
  - zitiidentities/status
  - zitijwtsigners/status
  - zitirouters/status
  - zitiserviceedgerouterpolicies/status
  - zitiservicepolicies/status
  - zitiservices/status
  - zitisidecars/status
  - zititerminators/status
  verbs:
  - get
  - patch
  - update
