#!/usr/bin/env python3
"""Builds docs/reference/<Kind>.md from config/crd/bases and config/samples.

Run after `make manifests`: hack/gen-crd-docs.py. The CI check `make docs-check` fails when the files differ.
Needs python3 and yq.
"""
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "reference"


def load(path):
    return json.loads(subprocess.check_output(["yq", "-o=json", ".", str(path)]))


def type_of(s):
    if s.get("x-kubernetes-int-or-string"):
        return "integer or string"
    t = s.get("type", "object")
    if t == "array":
        return "list of " + type_of(s.get("items", {}))
    if t == "object" and "additionalProperties" in s:
        return "map of " + type_of(s["additionalProperties"])
    return t


def notes(s):
    n = []
    if s.get("enum"):
        n.append("One of: " + ", ".join(f"`{e}`" for e in s["enum"]) + ".")
    it = s.get("items", {})
    if it.get("enum"):
        n.append("Each item is one of: " + ", ".join(f"`{e}`" for e in it["enum"]) + ".")
    for key, label in (("minimum", "Minimum"), ("maximum", "Maximum")):
        if key in s:
            n.append(f"{label} {s[key]}.")
        if key in it:
            n.append(f"Each item: {label.lower()} {it[key]}.")
    for key, label in (("minLength", "Minimum length"), ("maxLength", "Maximum length"),
                       ("minItems", "Minimum items"), ("maxItems", "Maximum items")):
        if key in s:
            n.append(f"{label} {s[key]}.")
    if "pattern" in s:
        n.append(f"Must match `{s['pattern']}`.")
    for rule in it.get("x-kubernetes-validations", []):
        n.append(f"Each item: {rule['message']}.")
    return n


def esc(text):
    return " ".join(text.split()).replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")


def rows(schema, prefix, required_here, out):
    for name, s in schema.get("properties", {}).items():
        path = f"{prefix}{name}"
        req = "yes" if name in required_here else "no"
        default = s.get("default")
        default = "" if default is None else f"`{json.dumps(default)}`"
        desc = esc(s.get("description", ""))
        extra = " ".join(notes(s))
        out.append((path, type_of(s), req, default, (desc + " " + extra).strip()))
        if s.get("type") == "object" and "properties" in s:
            rows(s, path + ".", set(s.get("required", [])), out)
        elif s.get("type") == "array" and s.get("items", {}).get("type") == "object" and "properties" in s["items"]:
            rows(s["items"], path + "[].", set(s["items"].get("required", [])), out)


def rules_of(schema, path=""):
    found = []
    for rule in schema.get("x-kubernetes-validations", []):
        found.append((path or "spec", rule["message"]))
    for name, s in schema.get("properties", {}).items():
        found += rules_of(s, f"{path}.{name}" if path else name)
    if "items" in schema:
        found += rules_of(schema["items"], path + "[]")
    return found


def table(header, data):
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    for r in data:
        lines.append("| " + " | ".join(f"`{r[0]}`" if i == 0 else c for i, c in enumerate(r)) + " |")
    return "\n".join(lines)


def render(crd):
    spec = crd["spec"]
    kind = spec["names"]["kind"]
    version = spec["versions"][0]
    schema = version["schema"]["openAPIV3Schema"]
    props = schema["properties"]
    short = ", ".join(f"`{s}`" for s in spec["names"].get("shortNames", [])) or "none"
    cats = ", ".join(f"`{c}`" for c in spec["names"].get("categories", [])) or "none"
    md = [f"# {kind}", "",
          "<!-- Generated by hack/gen-crd-docs.py from the CRD. Do not edit. -->", "",
          f"| | |", "|---|---|",
          f"| API version | `{spec['group']}/{version['name']}` |",
          f"| Scope | {spec['scope']} |",
          f"| Short name | {short} |",
          f"| Category | {cats} |",
          f"| Plural | `{spec['names']['plural']}` |", ""]

    cols = version.get("additionalPrinterColumns", [])
    if cols:
        md += ["## `kubectl get` columns", "",
               table(["Column", "Shown", "Source"],
                     [(c["name"], "with `-o wide`" if c.get("priority") else "always", f"`{c['jsonPath']}`") for c in cols]), ""]

    md += ["## Spec", ""]
    r = []
    rows(props["spec"], "spec.", set(props["spec"].get("required", [])), r)
    md += [table(["Field", "Type", "Required", "Default", "Description"], r), ""]

    rules = rules_of(props["spec"])
    if rules:
        md += ["## Validation rules", "", "The API server rejects a resource that breaks one of these rules.", ""]
        md += [f"- `{p}`: {m}" for p, m in rules] + [""]

    md += ["## Status", ""]
    r = []
    rows(props["status"], "status.", set(), r)
    md += [table(["Field", "Type", "Description"], [(a, b, e) for a, b, _, _, e in r]), ""]
    md += ["Conditions and their reasons are listed in [Conditions and reasons](../conditions.md).", ""]

    samples = sorted((ROOT / "config" / "samples").glob(f"*_{version['name']}_{kind.lower()}.yaml"))
    if samples:
        sample = samples[0]
        md += ["## Example", "", "```yaml", sample.read_text().rstrip(), "```", ""]
    return kind, "\n".join(md)


def main():
    check = "--check" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    changed = []
    kinds = []
    for path in sorted((ROOT / "config" / "crd" / "bases").glob("*.yaml")):
        kind, text = render(load(path))
        target = OUT / f"{kind}.md"
        old = target.read_text() if target.exists() else None
        if old != text + "\n":
            changed.append(target.name)
            if not check:
                target.write_text(text + "\n")
        kinds.append(kind)
    if check and changed:
        print("out of date, run hack/gen-crd-docs.py:", ", ".join(changed), file=sys.stderr)
        sys.exit(1)


main()
