apiVersion: alialjaffer.ziti/v1alpha1
kind: ZitiCA
metadata:
  labels:
    app.kubernetes.io/name: ziti-operator
    app.kubernetes.io/managed-by: kustomize
  name: zitica-sample
spec:
  # TODO(user): Add fields here
