apiVersion: alialjaffer.ziti/v1alpha1
kind: ZitiRouter
metadata:
  labels:
    app.kubernetes.io/name: ziti-operator
    app.kubernetes.io/managed-by: kustomize
  name: zitirouter-sample
spec:
  roleAttributes: [edge]
  tunnelerEnabled: true
  advertisedAddress: vm1.example.com
  enrollmentSecretRef: {namespace: default, name: zitirouter-sample-enrollment}
