apiVersion: alialjaffer.ziti/v1alpha1
kind: ZitiEdgeRouterPolicy
metadata:
  labels:
    app.kubernetes.io/name: ziti-operator
    app.kubernetes.io/managed-by: kustomize
  name: zitiedgerouterpolicy-sample
spec:
  # TODO(user): Add fields here
