## Append samples of your project ##
resources:
- ziti_v1alpha1_ziticonnection.yaml
- ziti_v1alpha1_zitiapp.yaml
- ziti_v1alpha1_zitiidentity.yaml
- ziti_v1alpha1_zitiaccesspolicy.yaml
- ziti_v1alpha1_zitijwtsigner.yaml
- ziti_v1alpha1_zitica.yaml
- ziti_v1alpha1_ziticonfig.yaml
- ziti_v1alpha1_zitiservice.yaml
- ziti_v1alpha1_zitiservicepolicy.yaml
- ziti_v1alpha1_zitiedgerouterpolicy.yaml
- ziti_v1alpha1_zitiserviceedgerouterpolicy.yaml
- ziti_v1alpha1_zitirouter.yaml
- ziti_v1alpha1_zititerminator.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
