apiVersion: ziti.alialjaffer.com/v1alpha1
kind: ZitiRouter
metadata:
  labels:
    app.kubernetes.io/name: ziti-operator
    app.kubernetes.io/managed-by: kustomize
  name: zitirouter-sample
spec:
  roleAttributes:
    - edge
  tunnelerEnabled: true
  advertisedAddress: vm1.example.com
  enrollmentSecretRef:
    namespace: default
    name: zitirouter-sample-enrollment
  # Uncomment to let the operator run the router in this cluster instead of writing manifests to the Secret.
  # deployment:
  #   namespace: routers
  #   serviceType: LoadBalancer
