apiVersion: alialjaffer.ziti/v1alpha1
kind: ZitiAccessPolicy
metadata:
  name: team-a
  namespace: default
spec:
  connectionRef: default
  identityRoles: ["#team-a"]
  serviceRoles: ["#team-a"]
  edgeRouters: [router-a]
