apiVersion: alialjaffer.com/v1alpha1
kind: ZitiApp
metadata:
  name: billing
  namespace: default
spec:
  zitiName: billing.example.com
  expose:
    addresses: [billing.example.com]
    ports: [443, "8000-8005"]
    protocols: [tcp]
  targets:
    - address: 10.0.0.5
    - address: 10.0.0.6
      cost: 10
  allow:
    groups: [team-a]
    identities: [alice]
  entryRouters: [edge-1]
