//go:build !ignore_autogenerated

/*
Copyright 2026 The openziti-operator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Allow) DeepCopyInto(out *Allow) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Identities != nil {
		in, out := &in.Identities, &out.Identities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Allow.
func (in *Allow) DeepCopy() *Allow {
	if in == nil {
		return nil
	}
	out := new(Allow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoEnrollment) DeepCopyInto(out *AutoEnrollment) {
	*out = *in
	if in.IdentityRoles != nil {
		in, out := &in.IdentityRoles, &out.IdentityRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoEnrollment.
func (in *AutoEnrollment) DeepCopy() *AutoEnrollment {
	if in == nil {
		return nil
	}
	out := new(AutoEnrollment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CABundle) DeepCopyInto(out *CABundle) {
	*out = *in
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CABundle.
func (in *CABundle) DeepCopy() *CABundle {
	if in == nil {
		return nil
	}
	out := new(CABundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAVerification) DeepCopyInto(out *CAVerification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAVerification.
func (in *CAVerification) DeepCopy() *CAVerification {
	if in == nil {
		return nil
	}
	out := new(CAVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertAuth) DeepCopyInto(out *CertAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertAuth.
func (in *CertAuth) DeepCopy() *CertAuth {
	if in == nil {
		return nil
	}
	out := new(CertAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSource) DeepCopyInto(out *CertificateSource) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSource.
func (in *CertificateSource) DeepCopy() *CertificateSource {
	if in == nil {
		return nil
	}
	out := new(CertificateSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionAuth) DeepCopyInto(out *ConnectionAuth) {
	*out = *in
	if in.Updb != nil {
		in, out := &in.Updb, &out.Updb
		*out = new(UpdbAuth)
		**out = **in
	}
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(CertAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionAuth.
func (in *ConnectionAuth) DeepCopy() *ConnectionAuth {
	if in == nil {
		return nil
	}
	out := new(ConnectionAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityIDs) DeepCopyInto(out *EntityIDs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityIDs.
func (in *EntityIDs) DeepCopy() *EntityIDs {
	if in == nil {
		return nil
	}
	out := new(EntityIDs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Expose) DeepCopyInto(out *Expose) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]intstr.IntOrString, len(*in))
		copy(*out, *in)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Expose.
func (in *Expose) DeepCopy() *Expose {
	if in == nil {
		return nil
	}
	out := new(Expose)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalIDClaim) DeepCopyInto(out *ExternalIDClaim) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalIDClaim.
func (in *ExternalIDClaim) DeepCopy() *ExternalIDClaim {
	if in == nil {
		return nil
	}
	out := new(ExternalIDClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwksEndpoint) DeepCopyInto(out *JwksEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwksEndpoint.
func (in *JwksEndpoint) DeepCopy() *JwksEndpoint {
	if in == nil {
		return nil
	}
	out := new(JwksEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesKeys) DeepCopyInto(out *KubernetesKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesKeys.
func (in *KubernetesKeys) DeepCopy() *KubernetesKeys {
	if in == nil {
		return nil
	}
	out := new(KubernetesKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerKeys) DeepCopyInto(out *SignerKeys) {
	*out = *in
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesKeys)
		**out = **in
	}
	if in.JwksEndpoint != nil {
		in, out := &in.JwksEndpoint, &out.JwksEndpoint
		*out = new(JwksEndpoint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerKeys.
func (in *SignerKeys) DeepCopy() *SignerKeys {
	if in == nil {
		return nil
	}
	out := new(SignerKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Terminator) DeepCopyInto(out *Terminator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Terminator.
func (in *Terminator) DeepCopy() *Terminator {
	if in == nil {
		return nil
	}
	out := new(Terminator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdbAuth) DeepCopyInto(out *UpdbAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdbAuth.
func (in *UpdbAuth) DeepCopy() *UpdbAuth {
	if in == nil {
		return nil
	}
	out := new(UpdbAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAccessPolicy) DeepCopyInto(out *ZitiAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAccessPolicy.
func (in *ZitiAccessPolicy) DeepCopy() *ZitiAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(ZitiAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAccessPolicyList) DeepCopyInto(out *ZitiAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAccessPolicyList.
func (in *ZitiAccessPolicyList) DeepCopy() *ZitiAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(ZitiAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAccessPolicySpec) DeepCopyInto(out *ZitiAccessPolicySpec) {
	*out = *in
	if in.IdentityRoles != nil {
		in, out := &in.IdentityRoles, &out.IdentityRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceRoles != nil {
		in, out := &in.ServiceRoles, &out.ServiceRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostureCheckRoles != nil {
		in, out := &in.PostureCheckRoles, &out.PostureCheckRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EdgeRouters != nil {
		in, out := &in.EdgeRouters, &out.EdgeRouters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAccessPolicySpec.
func (in *ZitiAccessPolicySpec) DeepCopy() *ZitiAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ZitiAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAccessPolicyStatus) DeepCopyInto(out *ZitiAccessPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAccessPolicyStatus.
func (in *ZitiAccessPolicyStatus) DeepCopy() *ZitiAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiApp) DeepCopyInto(out *ZitiApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiApp.
func (in *ZitiApp) DeepCopy() *ZitiApp {
	if in == nil {
		return nil
	}
	out := new(ZitiApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAppList) DeepCopyInto(out *ZitiAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAppList.
func (in *ZitiAppList) DeepCopy() *ZitiAppList {
	if in == nil {
		return nil
	}
	out := new(ZitiAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAppSpec) DeepCopyInto(out *ZitiAppSpec) {
	*out = *in
	in.Expose.DeepCopyInto(&out.Expose)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]Target, len(*in))
		copy(*out, *in)
	}
	in.Allow.DeepCopyInto(&out.Allow)
	if in.MemberOf != nil {
		in, out := &in.MemberOf, &out.MemberOf
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EntryRouters != nil {
		in, out := &in.EntryRouters, &out.EntryRouters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAppSpec.
func (in *ZitiAppSpec) DeepCopy() *ZitiAppSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAppStatus) DeepCopyInto(out *ZitiAppStatus) {
	*out = *in
	out.IDs = in.IDs
	if in.Terminators != nil {
		in, out := &in.Terminators, &out.Terminators
		*out = make([]Terminator, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAppStatus.
func (in *ZitiAppStatus) DeepCopy() *ZitiAppStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiCA) DeepCopyInto(out *ZitiCA) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiCA.
func (in *ZitiCA) DeepCopy() *ZitiCA {
	if in == nil {
		return nil
	}
	out := new(ZitiCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiCA) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiCAList) DeepCopyInto(out *ZitiCAList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiCA, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiCAList.
func (in *ZitiCAList) DeepCopy() *ZitiCAList {
	if in == nil {
		return nil
	}
	out := new(ZitiCAList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiCAList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiCASpec) DeepCopyInto(out *ZitiCASpec) {
	*out = *in
	out.Certificate = in.Certificate
	out.Verification = in.Verification
	if in.AuthEnabled != nil {
		in, out := &in.AuthEnabled, &out.AuthEnabled
		*out = new(bool)
		**out = **in
	}
	out.ExternalIDClaim = in.ExternalIDClaim
	if in.AutoEnrollment != nil {
		in, out := &in.AutoEnrollment, &out.AutoEnrollment
		*out = new(AutoEnrollment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiCASpec.
func (in *ZitiCASpec) DeepCopy() *ZitiCASpec {
	if in == nil {
		return nil
	}
	out := new(ZitiCASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiCAStatus) DeepCopyInto(out *ZitiCAStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiCAStatus.
func (in *ZitiCAStatus) DeepCopy() *ZitiCAStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiCAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConnection) DeepCopyInto(out *ZitiConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConnection.
func (in *ZitiConnection) DeepCopy() *ZitiConnection {
	if in == nil {
		return nil
	}
	out := new(ZitiConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConnectionList) DeepCopyInto(out *ZitiConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConnectionList.
func (in *ZitiConnectionList) DeepCopy() *ZitiConnectionList {
	if in == nil {
		return nil
	}
	out := new(ZitiConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConnectionSpec) DeepCopyInto(out *ZitiConnectionSpec) {
	*out = *in
	out.CABundle = in.CABundle
	in.Auth.DeepCopyInto(&out.Auth)
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HostingRouters != nil {
		in, out := &in.HostingRouters, &out.HostingRouters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultEdgeRouters != nil {
		in, out := &in.DefaultEdgeRouters, &out.DefaultEdgeRouters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConnectionSpec.
func (in *ZitiConnectionSpec) DeepCopy() *ZitiConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConnectionStatus) DeepCopyInto(out *ZitiConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConnectionStatus.
func (in *ZitiConnectionStatus) DeepCopy() *ZitiConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiIdentity) DeepCopyInto(out *ZitiIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiIdentity.
func (in *ZitiIdentity) DeepCopy() *ZitiIdentity {
	if in == nil {
		return nil
	}
	out := new(ZitiIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiIdentityList) DeepCopyInto(out *ZitiIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiIdentityList.
func (in *ZitiIdentityList) DeepCopy() *ZitiIdentityList {
	if in == nil {
		return nil
	}
	out := new(ZitiIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiIdentitySpec) DeepCopyInto(out *ZitiIdentitySpec) {
	*out = *in
	if in.RoleAttributes != nil {
		in, out := &in.RoleAttributes, &out.RoleAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiIdentitySpec.
func (in *ZitiIdentitySpec) DeepCopy() *ZitiIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(ZitiIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiIdentityStatus) DeepCopyInto(out *ZitiIdentityStatus) {
	*out = *in
	if in.EnrollmentExpiresAt != nil {
		in, out := &in.EnrollmentExpiresAt, &out.EnrollmentExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.CertNotAfter != nil {
		in, out := &in.CertNotAfter, &out.CertNotAfter
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiIdentityStatus.
func (in *ZitiIdentityStatus) DeepCopy() *ZitiIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiJwtSigner) DeepCopyInto(out *ZitiJwtSigner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiJwtSigner.
func (in *ZitiJwtSigner) DeepCopy() *ZitiJwtSigner {
	if in == nil {
		return nil
	}
	out := new(ZitiJwtSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiJwtSigner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiJwtSignerList) DeepCopyInto(out *ZitiJwtSignerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiJwtSigner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiJwtSignerList.
func (in *ZitiJwtSignerList) DeepCopy() *ZitiJwtSignerList {
	if in == nil {
		return nil
	}
	out := new(ZitiJwtSignerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiJwtSignerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiJwtSignerSpec) DeepCopyInto(out *ZitiJwtSignerSpec) {
	*out = *in
	if in.UseExternalID != nil {
		in, out := &in.UseExternalID, &out.UseExternalID
		*out = new(bool)
		**out = **in
	}
	in.Keys.DeepCopyInto(&out.Keys)
	if in.CreateAuthPolicy != nil {
		in, out := &in.CreateAuthPolicy, &out.CreateAuthPolicy
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiJwtSignerSpec.
func (in *ZitiJwtSignerSpec) DeepCopy() *ZitiJwtSignerSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiJwtSignerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiJwtSignerStatus) DeepCopyInto(out *ZitiJwtSignerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiJwtSignerStatus.
func (in *ZitiJwtSignerStatus) DeepCopy() *ZitiJwtSignerStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiJwtSignerStatus)
	in.DeepCopyInto(out)
	return out
}
