//go:build !ignore_autogenerated

/*
Copyright 2026 The openziti-operator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Allow) DeepCopyInto(out *Allow) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Identities != nil {
		in, out := &in.Identities, &out.Identities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Allow.
func (in *Allow) DeepCopy() *Allow {
	if in == nil {
		return nil
	}
	out := new(Allow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoEnrollment) DeepCopyInto(out *AutoEnrollment) {
	*out = *in
	if in.IdentityRoles != nil {
		in, out := &in.IdentityRoles, &out.IdentityRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoEnrollment.
func (in *AutoEnrollment) DeepCopy() *AutoEnrollment {
	if in == nil {
		return nil
	}
	out := new(AutoEnrollment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CABundle) DeepCopyInto(out *CABundle) {
	*out = *in
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CABundle.
func (in *CABundle) DeepCopy() *CABundle {
	if in == nil {
		return nil
	}
	out := new(CABundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAVerification) DeepCopyInto(out *CAVerification) {
	*out = *in
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(VerificationIssuer)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAVerification.
func (in *CAVerification) DeepCopy() *CAVerification {
	if in == nil {
		return nil
	}
	out := new(CAVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertAuth) DeepCopyInto(out *CertAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertAuth.
func (in *CertAuth) DeepCopy() *CertAuth {
	if in == nil {
		return nil
	}
	out := new(CertAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateIssuerRef) DeepCopyInto(out *CertificateIssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateIssuerRef.
func (in *CertificateIssuerRef) DeepCopy() *CertificateIssuerRef {
	if in == nil {
		return nil
	}
	out := new(CertificateIssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSource) DeepCopyInto(out *CertificateSource) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSource.
func (in *CertificateSource) DeepCopy() *CertificateSource {
	if in == nil {
		return nil
	}
	out := new(CertificateSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionAuth) DeepCopyInto(out *ConnectionAuth) {
	*out = *in
	if in.Updb != nil {
		in, out := &in.Updb, &out.Updb
		*out = new(UpdbAuth)
		**out = **in
	}
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(CertAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionAuth.
func (in *ConnectionAuth) DeepCopy() *ConnectionAuth {
	if in == nil {
		return nil
	}
	out := new(ConnectionAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityIDs) DeepCopyInto(out *EntityIDs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityIDs.
func (in *EntityIDs) DeepCopy() *EntityIDs {
	if in == nil {
		return nil
	}
	out := new(EntityIDs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntitySpec) DeepCopyInto(out *EntitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntitySpec.
func (in *EntitySpec) DeepCopy() *EntitySpec {
	if in == nil {
		return nil
	}
	out := new(EntitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityStatus) DeepCopyInto(out *EntityStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityStatus.
func (in *EntityStatus) DeepCopy() *EntityStatus {
	if in == nil {
		return nil
	}
	out := new(EntityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Expose) DeepCopyInto(out *Expose) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]intstr.IntOrString, len(*in))
		copy(*out, *in)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Expose.
func (in *Expose) DeepCopy() *Expose {
	if in == nil {
		return nil
	}
	out := new(Expose)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalIDClaim) DeepCopyInto(out *ExternalIDClaim) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalIDClaim.
func (in *ExternalIDClaim) DeepCopy() *ExternalIDClaim {
	if in == nil {
		return nil
	}
	out := new(ExternalIDClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwksEndpoint) DeepCopyInto(out *JwksEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwksEndpoint.
func (in *JwksEndpoint) DeepCopy() *JwksEndpoint {
	if in == nil {
		return nil
	}
	out := new(JwksEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesKeys) DeepCopyInto(out *KubernetesKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesKeys.
func (in *KubernetesKeys) DeepCopy() *KubernetesKeys {
	if in == nil {
		return nil
	}
	out := new(KubernetesKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerKeys) DeepCopyInto(out *SignerKeys) {
	*out = *in
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesKeys)
		**out = **in
	}
	if in.JwksEndpoint != nil {
		in, out := &in.JwksEndpoint, &out.JwksEndpoint
		*out = new(JwksEndpoint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerKeys.
func (in *SignerKeys) DeepCopy() *SignerKeys {
	if in == nil {
		return nil
	}
	out := new(SignerKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Terminator) DeepCopyInto(out *Terminator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Terminator.
func (in *Terminator) DeepCopy() *Terminator {
	if in == nil {
		return nil
	}
	out := new(Terminator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdbAuth) DeepCopyInto(out *UpdbAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdbAuth.
func (in *UpdbAuth) DeepCopy() *UpdbAuth {
	if in == nil {
		return nil
	}
	out := new(UpdbAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationIssuer) DeepCopyInto(out *VerificationIssuer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationIssuer.
func (in *VerificationIssuer) DeepCopy() *VerificationIssuer {
	if in == nil {
		return nil
	}
	out := new(VerificationIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadCertificate) DeepCopyInto(out *WorkloadCertificate) {
	*out = *in
	out.IssuerRef = in.IssuerRef
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadCertificate.
func (in *WorkloadCertificate) DeepCopy() *WorkloadCertificate {
	if in == nil {
		return nil
	}
	out := new(WorkloadCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAccessPolicy) DeepCopyInto(out *ZitiAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAccessPolicy.
func (in *ZitiAccessPolicy) DeepCopy() *ZitiAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(ZitiAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAccessPolicyList) DeepCopyInto(out *ZitiAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAccessPolicyList.
func (in *ZitiAccessPolicyList) DeepCopy() *ZitiAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(ZitiAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAccessPolicySpec) DeepCopyInto(out *ZitiAccessPolicySpec) {
	*out = *in
	if in.IdentityRoles != nil {
		in, out := &in.IdentityRoles, &out.IdentityRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceRoles != nil {
		in, out := &in.ServiceRoles, &out.ServiceRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostureCheckRoles != nil {
		in, out := &in.PostureCheckRoles, &out.PostureCheckRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EdgeRouters != nil {
		in, out := &in.EdgeRouters, &out.EdgeRouters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAccessPolicySpec.
func (in *ZitiAccessPolicySpec) DeepCopy() *ZitiAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ZitiAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAccessPolicyStatus) DeepCopyInto(out *ZitiAccessPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAccessPolicyStatus.
func (in *ZitiAccessPolicyStatus) DeepCopy() *ZitiAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiApp) DeepCopyInto(out *ZitiApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiApp.
func (in *ZitiApp) DeepCopy() *ZitiApp {
	if in == nil {
		return nil
	}
	out := new(ZitiApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAppList) DeepCopyInto(out *ZitiAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAppList.
func (in *ZitiAppList) DeepCopy() *ZitiAppList {
	if in == nil {
		return nil
	}
	out := new(ZitiAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAppSpec) DeepCopyInto(out *ZitiAppSpec) {
	*out = *in
	in.Expose.DeepCopyInto(&out.Expose)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]Target, len(*in))
		copy(*out, *in)
	}
	in.Allow.DeepCopyInto(&out.Allow)
	if in.MemberOf != nil {
		in, out := &in.MemberOf, &out.MemberOf
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EntryRouters != nil {
		in, out := &in.EntryRouters, &out.EntryRouters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAppSpec.
func (in *ZitiAppSpec) DeepCopy() *ZitiAppSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiAppStatus) DeepCopyInto(out *ZitiAppStatus) {
	*out = *in
	out.IDs = in.IDs
	if in.Terminators != nil {
		in, out := &in.Terminators, &out.Terminators
		*out = make([]Terminator, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiAppStatus.
func (in *ZitiAppStatus) DeepCopy() *ZitiAppStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiCA) DeepCopyInto(out *ZitiCA) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiCA.
func (in *ZitiCA) DeepCopy() *ZitiCA {
	if in == nil {
		return nil
	}
	out := new(ZitiCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiCA) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiCAList) DeepCopyInto(out *ZitiCAList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiCA, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiCAList.
func (in *ZitiCAList) DeepCopy() *ZitiCAList {
	if in == nil {
		return nil
	}
	out := new(ZitiCAList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiCAList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiCASpec) DeepCopyInto(out *ZitiCASpec) {
	*out = *in
	out.Certificate = in.Certificate
	in.Verification.DeepCopyInto(&out.Verification)
	if in.AuthEnabled != nil {
		in, out := &in.AuthEnabled, &out.AuthEnabled
		*out = new(bool)
		**out = **in
	}
	out.ExternalIDClaim = in.ExternalIDClaim
	if in.AutoEnrollment != nil {
		in, out := &in.AutoEnrollment, &out.AutoEnrollment
		*out = new(AutoEnrollment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiCASpec.
func (in *ZitiCASpec) DeepCopy() *ZitiCASpec {
	if in == nil {
		return nil
	}
	out := new(ZitiCASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiCAStatus) DeepCopyInto(out *ZitiCAStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiCAStatus.
func (in *ZitiCAStatus) DeepCopy() *ZitiCAStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiCAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConfig) DeepCopyInto(out *ZitiConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConfig.
func (in *ZitiConfig) DeepCopy() *ZitiConfig {
	if in == nil {
		return nil
	}
	out := new(ZitiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConfigList) DeepCopyInto(out *ZitiConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConfigList.
func (in *ZitiConfigList) DeepCopy() *ZitiConfigList {
	if in == nil {
		return nil
	}
	out := new(ZitiConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConfigSpec) DeepCopyInto(out *ZitiConfigSpec) {
	*out = *in
	out.EntitySpec = in.EntitySpec
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConfigSpec.
func (in *ZitiConfigSpec) DeepCopy() *ZitiConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConfigStatus) DeepCopyInto(out *ZitiConfigStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConfigStatus.
func (in *ZitiConfigStatus) DeepCopy() *ZitiConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConnection) DeepCopyInto(out *ZitiConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConnection.
func (in *ZitiConnection) DeepCopy() *ZitiConnection {
	if in == nil {
		return nil
	}
	out := new(ZitiConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConnectionList) DeepCopyInto(out *ZitiConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConnectionList.
func (in *ZitiConnectionList) DeepCopy() *ZitiConnectionList {
	if in == nil {
		return nil
	}
	out := new(ZitiConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConnectionSpec) DeepCopyInto(out *ZitiConnectionSpec) {
	*out = *in
	out.CABundle = in.CABundle
	in.Auth.DeepCopyInto(&out.Auth)
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HostingRouters != nil {
		in, out := &in.HostingRouters, &out.HostingRouters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EntryRouters != nil {
		in, out := &in.EntryRouters, &out.EntryRouters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultEdgeRouters != nil {
		in, out := &in.DefaultEdgeRouters, &out.DefaultEdgeRouters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConnectionSpec.
func (in *ZitiConnectionSpec) DeepCopy() *ZitiConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiConnectionStatus) DeepCopyInto(out *ZitiConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiConnectionStatus.
func (in *ZitiConnectionStatus) DeepCopy() *ZitiConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiEdgeRouterPolicy) DeepCopyInto(out *ZitiEdgeRouterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiEdgeRouterPolicy.
func (in *ZitiEdgeRouterPolicy) DeepCopy() *ZitiEdgeRouterPolicy {
	if in == nil {
		return nil
	}
	out := new(ZitiEdgeRouterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiEdgeRouterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiEdgeRouterPolicyList) DeepCopyInto(out *ZitiEdgeRouterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiEdgeRouterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiEdgeRouterPolicyList.
func (in *ZitiEdgeRouterPolicyList) DeepCopy() *ZitiEdgeRouterPolicyList {
	if in == nil {
		return nil
	}
	out := new(ZitiEdgeRouterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiEdgeRouterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiEdgeRouterPolicySpec) DeepCopyInto(out *ZitiEdgeRouterPolicySpec) {
	*out = *in
	out.EntitySpec = in.EntitySpec
	if in.IdentityRoles != nil {
		in, out := &in.IdentityRoles, &out.IdentityRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EdgeRouterRoles != nil {
		in, out := &in.EdgeRouterRoles, &out.EdgeRouterRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiEdgeRouterPolicySpec.
func (in *ZitiEdgeRouterPolicySpec) DeepCopy() *ZitiEdgeRouterPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ZitiEdgeRouterPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiEdgeRouterPolicyStatus) DeepCopyInto(out *ZitiEdgeRouterPolicyStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiEdgeRouterPolicyStatus.
func (in *ZitiEdgeRouterPolicyStatus) DeepCopy() *ZitiEdgeRouterPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiEdgeRouterPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiIdentity) DeepCopyInto(out *ZitiIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiIdentity.
func (in *ZitiIdentity) DeepCopy() *ZitiIdentity {
	if in == nil {
		return nil
	}
	out := new(ZitiIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiIdentityList) DeepCopyInto(out *ZitiIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiIdentityList.
func (in *ZitiIdentityList) DeepCopy() *ZitiIdentityList {
	if in == nil {
		return nil
	}
	out := new(ZitiIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiIdentitySpec) DeepCopyInto(out *ZitiIdentitySpec) {
	*out = *in
	if in.RoleAttributes != nil {
		in, out := &in.RoleAttributes, &out.RoleAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(WorkloadCertificate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiIdentitySpec.
func (in *ZitiIdentitySpec) DeepCopy() *ZitiIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(ZitiIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiIdentityStatus) DeepCopyInto(out *ZitiIdentityStatus) {
	*out = *in
	if in.EnrollmentExpiresAt != nil {
		in, out := &in.EnrollmentExpiresAt, &out.EnrollmentExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.CertNotAfter != nil {
		in, out := &in.CertNotAfter, &out.CertNotAfter
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiIdentityStatus.
func (in *ZitiIdentityStatus) DeepCopy() *ZitiIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiJwtSigner) DeepCopyInto(out *ZitiJwtSigner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiJwtSigner.
func (in *ZitiJwtSigner) DeepCopy() *ZitiJwtSigner {
	if in == nil {
		return nil
	}
	out := new(ZitiJwtSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiJwtSigner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiJwtSignerList) DeepCopyInto(out *ZitiJwtSignerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiJwtSigner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiJwtSignerList.
func (in *ZitiJwtSignerList) DeepCopy() *ZitiJwtSignerList {
	if in == nil {
		return nil
	}
	out := new(ZitiJwtSignerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiJwtSignerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiJwtSignerSpec) DeepCopyInto(out *ZitiJwtSignerSpec) {
	*out = *in
	if in.UseExternalID != nil {
		in, out := &in.UseExternalID, &out.UseExternalID
		*out = new(bool)
		**out = **in
	}
	in.Keys.DeepCopyInto(&out.Keys)
	if in.CreateAuthPolicy != nil {
		in, out := &in.CreateAuthPolicy, &out.CreateAuthPolicy
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiJwtSignerSpec.
func (in *ZitiJwtSignerSpec) DeepCopy() *ZitiJwtSignerSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiJwtSignerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiJwtSignerStatus) DeepCopyInto(out *ZitiJwtSignerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiJwtSignerStatus.
func (in *ZitiJwtSignerStatus) DeepCopy() *ZitiJwtSignerStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiJwtSignerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiRouter) DeepCopyInto(out *ZitiRouter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiRouter.
func (in *ZitiRouter) DeepCopy() *ZitiRouter {
	if in == nil {
		return nil
	}
	out := new(ZitiRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiRouter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiRouterDeployment) DeepCopyInto(out *ZitiRouterDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiRouterDeployment.
func (in *ZitiRouterDeployment) DeepCopy() *ZitiRouterDeployment {
	if in == nil {
		return nil
	}
	out := new(ZitiRouterDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiRouterList) DeepCopyInto(out *ZitiRouterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiRouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiRouterList.
func (in *ZitiRouterList) DeepCopy() *ZitiRouterList {
	if in == nil {
		return nil
	}
	out := new(ZitiRouterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiRouterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiRouterSpec) DeepCopyInto(out *ZitiRouterSpec) {
	*out = *in
	if in.RoleAttributes != nil {
		in, out := &in.RoleAttributes, &out.RoleAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnrollmentSecretRef != nil {
		in, out := &in.EnrollmentSecretRef, &out.EnrollmentSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(ZitiRouterDeployment)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiRouterSpec.
func (in *ZitiRouterSpec) DeepCopy() *ZitiRouterSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiRouterStatus) DeepCopyInto(out *ZitiRouterStatus) {
	*out = *in
	if in.EnrollmentExpiresAt != nil {
		in, out := &in.EnrollmentExpiresAt, &out.EnrollmentExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiRouterStatus.
func (in *ZitiRouterStatus) DeepCopy() *ZitiRouterStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiRouterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiService) DeepCopyInto(out *ZitiService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiService.
func (in *ZitiService) DeepCopy() *ZitiService {
	if in == nil {
		return nil
	}
	out := new(ZitiService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServiceEdgeRouterPolicy) DeepCopyInto(out *ZitiServiceEdgeRouterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServiceEdgeRouterPolicy.
func (in *ZitiServiceEdgeRouterPolicy) DeepCopy() *ZitiServiceEdgeRouterPolicy {
	if in == nil {
		return nil
	}
	out := new(ZitiServiceEdgeRouterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiServiceEdgeRouterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServiceEdgeRouterPolicyList) DeepCopyInto(out *ZitiServiceEdgeRouterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiServiceEdgeRouterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServiceEdgeRouterPolicyList.
func (in *ZitiServiceEdgeRouterPolicyList) DeepCopy() *ZitiServiceEdgeRouterPolicyList {
	if in == nil {
		return nil
	}
	out := new(ZitiServiceEdgeRouterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiServiceEdgeRouterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServiceEdgeRouterPolicySpec) DeepCopyInto(out *ZitiServiceEdgeRouterPolicySpec) {
	*out = *in
	out.EntitySpec = in.EntitySpec
	if in.ServiceRoles != nil {
		in, out := &in.ServiceRoles, &out.ServiceRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EdgeRouterRoles != nil {
		in, out := &in.EdgeRouterRoles, &out.EdgeRouterRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServiceEdgeRouterPolicySpec.
func (in *ZitiServiceEdgeRouterPolicySpec) DeepCopy() *ZitiServiceEdgeRouterPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ZitiServiceEdgeRouterPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServiceEdgeRouterPolicyStatus) DeepCopyInto(out *ZitiServiceEdgeRouterPolicyStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServiceEdgeRouterPolicyStatus.
func (in *ZitiServiceEdgeRouterPolicyStatus) DeepCopy() *ZitiServiceEdgeRouterPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiServiceEdgeRouterPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServiceList) DeepCopyInto(out *ZitiServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServiceList.
func (in *ZitiServiceList) DeepCopy() *ZitiServiceList {
	if in == nil {
		return nil
	}
	out := new(ZitiServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServicePolicy) DeepCopyInto(out *ZitiServicePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServicePolicy.
func (in *ZitiServicePolicy) DeepCopy() *ZitiServicePolicy {
	if in == nil {
		return nil
	}
	out := new(ZitiServicePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiServicePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServicePolicyList) DeepCopyInto(out *ZitiServicePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiServicePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServicePolicyList.
func (in *ZitiServicePolicyList) DeepCopy() *ZitiServicePolicyList {
	if in == nil {
		return nil
	}
	out := new(ZitiServicePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiServicePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServicePolicySpec) DeepCopyInto(out *ZitiServicePolicySpec) {
	*out = *in
	out.EntitySpec = in.EntitySpec
	if in.IdentityRoles != nil {
		in, out := &in.IdentityRoles, &out.IdentityRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceRoles != nil {
		in, out := &in.ServiceRoles, &out.ServiceRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostureCheckRoles != nil {
		in, out := &in.PostureCheckRoles, &out.PostureCheckRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServicePolicySpec.
func (in *ZitiServicePolicySpec) DeepCopy() *ZitiServicePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ZitiServicePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServicePolicyStatus) DeepCopyInto(out *ZitiServicePolicyStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServicePolicyStatus.
func (in *ZitiServicePolicyStatus) DeepCopy() *ZitiServicePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiServicePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServiceSpec) DeepCopyInto(out *ZitiServiceSpec) {
	*out = *in
	out.EntitySpec = in.EntitySpec
	if in.RoleAttributes != nil {
		in, out := &in.RoleAttributes, &out.RoleAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Configs != nil {
		in, out := &in.Configs, &out.Configs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EncryptionRequired != nil {
		in, out := &in.EncryptionRequired, &out.EncryptionRequired
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServiceSpec.
func (in *ZitiServiceSpec) DeepCopy() *ZitiServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiServiceStatus) DeepCopyInto(out *ZitiServiceStatus) {
	*out = *in
	in.EntityStatus.DeepCopyInto(&out.EntityStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiServiceStatus.
func (in *ZitiServiceStatus) DeepCopy() *ZitiServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiSidecar) DeepCopyInto(out *ZitiSidecar) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiSidecar.
func (in *ZitiSidecar) DeepCopy() *ZitiSidecar {
	if in == nil {
		return nil
	}
	out := new(ZitiSidecar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiSidecar) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiSidecarList) DeepCopyInto(out *ZitiSidecarList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiSidecar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiSidecarList.
func (in *ZitiSidecarList) DeepCopy() *ZitiSidecarList {
	if in == nil {
		return nil
	}
	out := new(ZitiSidecarList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiSidecarList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiSidecarSpec) DeepCopyInto(out *ZitiSidecarSpec) {
	*out = *in
	if in.ManifestSecretRef != nil {
		in, out := &in.ManifestSecretRef, &out.ManifestSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiSidecarSpec.
func (in *ZitiSidecarSpec) DeepCopy() *ZitiSidecarSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiSidecarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiSidecarStatus) DeepCopyInto(out *ZitiSidecarStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiSidecarStatus.
func (in *ZitiSidecarStatus) DeepCopy() *ZitiSidecarStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiSidecarStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiTerminator) DeepCopyInto(out *ZitiTerminator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiTerminator.
func (in *ZitiTerminator) DeepCopy() *ZitiTerminator {
	if in == nil {
		return nil
	}
	out := new(ZitiTerminator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiTerminator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiTerminatorList) DeepCopyInto(out *ZitiTerminatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZitiTerminator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiTerminatorList.
func (in *ZitiTerminatorList) DeepCopy() *ZitiTerminatorList {
	if in == nil {
		return nil
	}
	out := new(ZitiTerminatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZitiTerminatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiTerminatorSpec) DeepCopyInto(out *ZitiTerminatorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiTerminatorSpec.
func (in *ZitiTerminatorSpec) DeepCopy() *ZitiTerminatorSpec {
	if in == nil {
		return nil
	}
	out := new(ZitiTerminatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZitiTerminatorStatus) DeepCopyInto(out *ZitiTerminatorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZitiTerminatorStatus.
func (in *ZitiTerminatorStatus) DeepCopy() *ZitiTerminatorStatus {
	if in == nil {
		return nil
	}
	out := new(ZitiTerminatorStatus)
	in.DeepCopyInto(out)
	return out
}
