apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.namespaced }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
{{- if .Values.rbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  name: {{ include "ziti-operator.resourceName" (dict "suffix" "manager-role" "context" $) }}
rules:
- nonResourceURLs:
  - /.well-known/openid-configuration
  - /openid/v1/jwks
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  {{- if not .Values.rbac.secretNamespaces }}
  - configmaps
  {{- end }}
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
{{- if not .Values.rbac.secretNamespaces }}
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
- apiGroups:
  - alialjaffer.ziti
  resources:
  - zitiaccesspolicies
  - zitiapps
  - ziticas
  - ziticonfigs
  - ziticonnections
  - zitiedgerouterpolicies
  - zitiidentities
  - zitijwtsigners
  - zitiserviceedgerouterpolicies
  - zitiservicepolicies
  - zitiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alialjaffer.ziti
  resources:
  - zitiaccesspolicies/finalizers
  - zitiapps/finalizers
  - ziticas/finalizers
  - ziticonfigs/finalizers
  - ziticonnections/finalizers
  - zitiedgerouterpolicies/finalizers
  - zitiidentities/finalizers
  - zitijwtsigners/finalizers
  - zitiserviceedgerouterpolicies/finalizers
  - zitiservicepolicies/finalizers
  - zitiservices/finalizers
  verbs:
  - update
- apiGroups:
  - alialjaffer.ziti
  resources:
  - zitiaccesspolicies/status
  - zitiapps/status
  - ziticas/status
  - ziticonfigs/status
  - ziticonnections/status
  - zitiedgerouterpolicies/status
  - zitiidentities/status
  - zitijwtsigners/status
  - zitiserviceedgerouterpolicies/status
  - zitiservicepolicies/status
  - zitiservices/status
  verbs:
  - get
  - patch
  - update
