{{- if include "ziti-operator.limitSecrets" . }}
{{- range $ns := splitList "," (include "ziti-operator.secretNamespaceList" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "ziti-operator.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ include "ziti-operator.resourceName" (dict "suffix" "secret-access" "context" $) }}
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [""]
  resources: [configmaps]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "ziti-operator.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ include "ziti-operator.resourceName" (dict "suffix" "secret-access" "context" $) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ziti-operator.resourceName" (dict "suffix" "secret-access" "context" $) }}
subjects:
- kind: ServiceAccount
  name: {{ include "ziti-operator.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
