apiVersion: v2
name: ziti-operator
description: A Helm chart to distribute ziti-operator
type: application

version: 0.2.0
appVersion: "0.2.0"

sources:
  - https://github.com/aliAljaffer/openziti-operator

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
